# Generated by Django 4.0.1 on 2022-01-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default='내용'),
            preserve_default=False,
        ),
    ]
